Add HITCON16 Sleepy Holder and Heart Attack writeups
ctfs/write-ups-2016 pull request #2799
Opened 2016-11-23 11:00 UTC by andigena

2016-11-24 01:36 UTC, ghost requested changes
Except for small fixes in the link formatting, looks pretty good!

2016-11-24 01:36 UTC, tjgerot commented on hitcon-ctf-2016/pwn/heart-attack-400/README.md
> +* [Writeup by the challenge author](https://github.com/mehQQ/public_writeup/tree/master/hitcon2016/HeartAttack)
May I suggest
`[NAME (Challenge Author)](https://github.com/mehQQ/public_writeup/tree/master/hitcon2016/HeartAttack)`
where you replace `NAME` with your own?

2016-11-24 01:36 UTC, tjgerot commented on hitcon-ctf-2016/pwn/sleepy-holder-300/README.md
> +* [Writeup by the challenge author](https://github.com/mehQQ/public_writeup/tree/master/hitcon2016/SleepyHolder)
Same suggestion as above.

2016-11-24 09:01 UTC, andigena commented on hitcon-ctf-2016/pwn/heart-attack-400/README.md
> +* [Writeup by the challenge author](https://github.com/mehQQ/public_writeup/tree/master/hitcon2016/HeartAttack)
Sure, I've made the changes.

2016-11-25 00:46 UTC, ghost approved these changes

2016-11-25 00:48 UTC, merged

2016-11-25 00:48 UTC, tjgerot commented
Thanks! It's always great to get write-ups from the author. Happy Thanksgiving.